[package]
name = "words"
version = "0.7.0"
authors = ["Peter Sonntag <peter@sonniger-tag.eu>"]
edition = "2024"
publish = false

[profile.release]
lto = true

[dependencies]
anyhow = "1"
rand = "0.9"
relm4 = { version = "0.10.0", features = ["libadwaita", "gnome_48"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1"
tr = { version = "0.1.11" }
gettext-rs = "0.7"
